# Generated by Django 2.1.7 on 2019-03-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.ImageField(upload_to='img/', verbose_name='1'),
        ),
    ]
