# Generated by Django 2.1.7 on 2019-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0004_auto_20190314_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.ImageField(upload_to='onlineshoppingapp/static/assets/img/'),
        ),
    ]
