# Generated by Django 2.1.7 on 2019-03-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190317_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='username',
            new_name='userid',
        ),
    ]
